services:
  api:
    build:
      context: .
      dockerfile: container/yactr-api/Dockerfile
      target: final
    ports:
      - "8080:8080"
    profiles:
      - development-full
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Minio__Endpoint=file-bucket:9000
      - Minio__AccessKey=yactr
      - Minio__SecretKey=yactr
      - ConnectionStrings__DatabaseContextConnection=Host=database;Database=yactr_dev;Username=yactr;Password=yactr;Port=5432

  database:
    environment:
      POSTGRES_USER: yactr
      POSTGRES_PASSWORD: yactr
    ports:
      - "5432:5432"
    volumes:
      - database-data:/var/lib/postgresql
    # Add build context to install extensions
    image: postgis/postgis:18-3.6
    platform: linux/amd64
    profiles:
      - test
      - development
      - development-full

  file-bucket:
    image: quay.io/minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: yactr
      MINIO_ROOT_PASSWORD: playground
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - file-bucket-data:/data
    profiles:
      - test
      - development
      - development-full

volumes:
  database-data:
  file-bucket-data:
